In [2]:
import pandas as pd
import glob
import os
import json
import numpy as np
import inspect
import sys
import math

In [3]:
df_w1 = pd.read_csv('../data/movez_questionnaire/W1_Main_questions.csv', sep=';', header=0)
df_w2 = pd.read_csv('../data/movez_questionnaire/W2_Main_questions.csv', sep=';', header=0)
df_w3 = pd.read_csv('../data/movez_questionnaire/W3_Main_questions.csv', sep=';', header=0)
df_w4 = pd.read_csv('../data/movez_questionnaire/W4_Main_questions.csv', sep=';', header=0)
df_w5 = pd.read_csv('../data/movez_questionnaire/W5_Main_questions.csv', sep=';', header=0)
df_w6 = pd.read_csv('../data/movez_questionnaire/W6_Main_questions.csv', sep=';', header=0)
df_w7 = pd.read_csv('../data/movez_questionnaire/W7_Main_questions.csv', sep=';', header=0)

/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1303281735.py:5: DtypeWarning: Columns (115,117,372,374,406,408,437,439,479,481,512,514,537,547,548,572,573,599,607,610) have mixed types. Specify dtype option on import or set low_memory=False.
  df_w5 = pd.read_csv('../data/movez_questionnaire/W5_Main_questions.csv', sep=';', header=0)
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1303281735.py:6: DtypeWarning: Columns (319,375,432,434,437,439,442,444,447,449,452,454,457,459,462,464,467,469,472,474,477,479,482,484,487,489) have mixed types. Specify dtype option on import or set low_memory=False.
  df_w6 = pd.read_csv('../data/movez_questionnaire/W6_Main_questions.csv', sep=';', header=0)

In [4]:
df_pp = pd.read_csv('../data/movez_metadata/Participant_Info.csv', sep=';', header=0)
df_final = df_pp[['Child']]
df_final

      Child
0       902
1       904
2       907
3       908
4       909
...     ...
1479   6180
1480   6181
1481   6182
1482   6183
1483   6186

[1484 rows x 1 columns]

## GEN_FAS REV 1

In [11]:
filter_col = [col for col in df_w2 if col.startswith('GEN_FAS')]
filter_col.append('Child')
filter_col = [filter_col[-1]] + filter_col[:-1]
df_fas_w2 = df_w2[filter_col]
print('w2', filter_col)

filter_col = [col for col in df_w4 if col.startswith('GEN_FAS')]
filter_col.append('Child')
filter_col = [filter_col[-1]] + filter_col[:-1]
df_fas_w4 = df_w4[filter_col]
print('w4',filter_col)

filter_col = [col for col in df_w6 if col.startswith('GEN_FAS')]
filter_col.append('Child')
filter_col = [filter_col[-1]] + filter_col[:-1]
df_fas_w6 = df_w6[filter_col]
print('w6', filter_col)

w2 ['Child', 'GEN_FAS_TriggerDate_1', 'GEN_FAS_Weekend_1', 'GEN_FAS_TriggerTime_1', 'GEN_FAS_GEN_FAS_computer_1', 'GEN_FAS_GEN_FAS_car_1', 'GEN_FAS_GEN_FAS_bathroom_1', 'GEN_FAS_GEN_FAS_vacation_1', 'GEN_FAS_GEN_FAS_ownroom_1', 'GEN_FAS_GEN_FAS_dishwasher_1']
w4 ['Child', 'GEN_FAS_TriggerDate', 'GEN_FAS_Weekend', 'GEN_FAS_TriggerTime', 'GEN_FAS_GEN_FAS_computer', 'GEN_FAS_GEN_FAS_car', 'GEN_FAS_GEN_FAS_bathroom', 'GEN_FAS_GEN_FAS_vacation', 'GEN_FAS_GEN_FAS_ownroom', 'GEN_FAS_GEN_FAS_dishwasher']
w6 ['Child', 'GEN_FAS_TriggerDate', 'GEN_FAS_Weekend', 'GEN_FAS_TriggerTime', 'GEN_FAS_computer', 'GEN_FAS_car', 'GEN_FAS_bathroom', 'GEN_FAS_vacation', 'GEN_FAS_ownroom', 'GEN_FAS_dishwasher']

In [25]:
# item 1
df_fas_item1 = df_pp[['Child']]
df_fas_item1['w2'] = df_fas_item1['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_computer_1'])
df_fas_item1['w4'] = df_fas_item1['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_computer'])
df_fas_item1['w6'] = df_fas_item1['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_computer'])

# item 2
df_fas_item2 = df_pp[['Child']]
df_fas_item2['w2'] = df_fas_item2['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_car_1'])
df_fas_item2['w4'] = df_fas_item2['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_car'])
df_fas_item2['w6'] = df_fas_item2['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_car'])

# item 3
df_fas_item3 = df_pp[['Child']]
df_fas_item3['w2'] = df_fas_item3['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_bathroom_1'])
df_fas_item3['w4'] = df_fas_item3['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_bathroom'])
df_fas_item3['w6'] = df_fas_item3['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_bathroom'])

# item 4
df_fas_item4 = df_pp[['Child']]
df_fas_item4['w2'] = df_fas_item4['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_vacation_1'])
df_fas_item4['w4'] = df_fas_item4['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_vacation'])
df_fas_item4['w6'] = df_fas_item4['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_vacation'])

# item 5
df_fas_item5 = df_pp[['Child']]
df_fas_item5['w2'] = df_fas_item5['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_ownroom_1'])
df_fas_item5['w4'] = df_fas_item5['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_ownroom'])
df_fas_item5['w6'] = df_fas_item5['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_ownroom'])

# item 6
df_fas_item6 = df_pp[['Child']]
df_fas_item6['w2'] = df_fas_item6['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_dishwasher_1'])
df_fas_item6['w4'] = df_fas_item6['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_dishwasher'])
df_fas_item6['w6'] = df_fas_item6['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_dishwasher'])

/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item1['w2'] = df_fas_item1['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_computer_1'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item1['w4'] = df_fas_item1['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_computer'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item1['w6'] = df_fas_item1['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_computer'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item2['w2'] = df_fas_item2['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_car_1'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item2['w4'] = df_fas_item2['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_car'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item2['w6'] = df_fas_item2['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_car'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item3['w2'] = df_fas_item3['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_bathroom_1'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item3['w4'] = df_fas_item3['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_bathroom'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item3['w6'] = df_fas_item3['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_bathroom'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item4['w2'] = df_fas_item4['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_vacation_1'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item4['w4'] = df_fas_item4['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_vacation'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item4['w6'] = df_fas_item4['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_vacation'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item5['w2'] = df_fas_item5['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_ownroom_1'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item5['w4'] = df_fas_item5['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_ownroom'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item5['w6'] = df_fas_item5['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_ownroom'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item6['w2'] = df_fas_item6['Child'].map(df_fas_w2.set_index('Child')['GEN_FAS_GEN_FAS_dishwasher_1'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item6['w4'] = df_fas_item6['Child'].map(df_fas_w4.set_index('Child')['GEN_FAS_GEN_FAS_dishwasher'])
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/620890458.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas_item6['w6'] = df_fas_item6['Child'].map(df_fas_w6.set_index('Child')['GEN_FAS_dishwasher'])

In [26]:
df_fas = df_pp[['Child']]
df_fas['item1'] = df_fas_item1[['w2', 'w4', 'w6']].mean(axis=1)
df_fas['item2'] = df_fas_item2[['w2', 'w4', 'w6']].mean(axis=1)
df_fas['item3'] = df_fas_item3[['w2', 'w4', 'w6']].mean(axis=1)
df_fas['item4'] = df_fas_item4[['w2', 'w4', 'w6']].mean(axis=1)
df_fas['item5'] = df_fas_item5[['w2', 'w4', 'w6']].mean(axis=1)
df_fas['item6'] = df_fas_item6[['w2', 'w4', 'w6']].mean(axis=1)


df_fas

/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1090694867.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas['item1'] = df_fas_item1[['w2', 'w4', 'w6']].mean(axis=1)
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1090694867.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas['item2'] = df_fas_item2[['w2', 'w4', 'w6']].mean(axis=1)
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1090694867.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas['item3'] = df_fas_item3[['w2', 'w4', 'w6']].mean(axis=1)
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1090694867.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas['item4'] = df_fas_item4[['w2', 'w4', 'w6']].mean(axis=1)
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1090694867.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas['item5'] = df_fas_item5[['w2', 'w4', 'w6']].mean(axis=1)
/var/folders/z2/s9qy78ps1kl1_9g5fgzy5tgw0000gn/T/ipykernel_51964/1090694867.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fas['item6'] = df_fas_item6[['w2', 'w4', 'w6']].mean(axis=1)

      Child  item1  item2  item3  item4  item5  item6
0       902    NaN    NaN    NaN    NaN    NaN    NaN
1       904    NaN    NaN    NaN    NaN    NaN    NaN
2       907    NaN    NaN    NaN    NaN    NaN    NaN
3       908    NaN    NaN    NaN    NaN    NaN    NaN
4       909    NaN    NaN    NaN    NaN    NaN    NaN
...     ...    ...    ...    ...    ...    ...    ...
1479   6180    3.0    2.0    2.0    0.0    1.0    1.0
1480   6181    1.0    2.0    1.0    2.0    1.0    1.0
1481   6182    1.0    0.0    1.0    2.0    0.0    0.0
1482   6183    NaN    NaN    NaN    NaN    NaN    NaN
1483   6186    2.0    0.0    1.0    1.0    0.0    1.0

[1484 rows x 7 columns]

In [27]:
df_fas.describe()

,Child,item1,item2,item3,item4,item5,item6
count,1484.000000,1318.000000,1318.000000,1318.000000,1318.000000,1318.000000,1318.000000
mean,3455.690701,2.690061,1.453718,1.238619,1.416161,0.921472,0.888088
std,1785.198001,0.634158,0.625439,0.493853,1.072004,0.263759,0.310219
min,902.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1714.750000,3.000000,1.000000,1.000000,0.625000,1.000000,1.000000
50%,2993.500000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000
75%,5438.250000,3.000000,2.000000,1.000000,2.000000,1.000000,1.000000
max,6186.000000,3.000000,2.000000,3.000000,3.000000,1.000000,1.000000

In [30]:
df_fas_sum = df_fas[['item1', 'item2', 'item3', 'item4', 'item5', 'item6']].sum(axis=1)
df_fas_sum.describe()

count    1484.000000
mean        7.645216
std         3.234638
min         0.000000
25%         7.000000
50%         8.000000
75%        10.000000
max        13.000000
dtype: float64